# Generated by Django 6.0.7 on 2026-07-31 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('sts_manager', 'STS Manager'), ('area_head', 'Area Head'), ('driver', 'Driver'), ('house_owner', 'House Owner'), ('landfill_manager', 'Landfill Manager'), ('truck_owner', 'Truck Owner'), ('admin', 'Admin')], default='house_owner', max_length=20),
        ),
        migrations.CreateModel(
            name='WasteCollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(help_text="User's location (can be coordinates or address)")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
