# Generated by Django 6.0.7 on 2026-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_role_wastecollectionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollectionrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='latitude',
            field=models.FloatField(default=0, help_text='Latitude of the location'),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='longitude',
            field=models.FloatField(default=0, help_text='Longitude of the location'),
        ),
        migrations.AlterField(
            model_name='wastecollectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
