# Generated by Django 6.0.7 on 2026-07-31 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_wastecollectionrequest_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_waste_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the waste', null=True, upload_to='waste_images/'),
        ),
    ]
