# Generated by Django 6.0.7 on 2026-07-31 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wastecollectionrequest_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight of the waste in kg'),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wastetype'),
        ),
    ]
