# Generated by Django 6.0.7 on 2026-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wastetype_wastecollectionrequest_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='description',
            field=models.TextField(blank=True, help_text='AI generated description of the waste', null=True),
        ),
    ]
