# Generated by Django 6.0.7 on 2026-07-31 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wastecollectionrequest_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_landfills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity_tonnes', models.FloatField(help_text='Maximum capacity in tonnes')),
                ('current_fill_tonnes', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('capacity_tonnes', models.FloatField(help_text='Maximum capacity in tonnes')),
                ('current_load_tonnes', models.FloatField(default=0.0)),
                ('hours_driven_today', models.FloatField(default=0.0)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck', to=settings.AUTH_USER_MODEL)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='api.landfill')),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('capacity_kg', models.FloatField(help_text='Maximum capacity in kg')),
                ('current_load_kg', models.FloatField(default=0.0)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van', to=settings.AUTH_USER_MODEL)),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vans', to='api.sts')),
            ],
        ),
    ]
