# Generated by Django 6.0.7 on 2026-07-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_landfill_sts_truck_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='max_trips_per_day',
            field=models.IntegerField(default=2, help_text='Maximum allowed trips per day'),
        ),
        migrations.AddField(
            model_name='van',
            name='trips_today',
            field=models.IntegerField(default=0, help_text='Number of trips completed today'),
        ),
    ]
