# Generated by Django 6.0.7 on 2026-07-31 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_van_max_trips_per_day_van_trips_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_weight_kg', models.FloatField(help_text="Weight logged by driver (automatically derived from van's current load)")),
                ('actual_weight_kg', models.FloatField(blank=True, help_text='Actual weight verified by STS Manager', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified - Match'), ('flagged', 'Verified - Discrepancy Flagged')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dump_requests', to='api.sts')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dump_requests', to='api.van')),
            ],
        ),
    ]
