# Generated by Django 6.0.7 on 2026-07-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField(default=0.0, help_text='Center latitude of the area')),
                ('longitude', models.FloatField(default=0.0, help_text='Center longitude of the area')),
                ('radius_km', models.FloatField(default=5.0, help_text='Radius of the area in kilometers')),
            ],
        ),
        migrations.AddField(
            model_name='sts',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sts_stations', to='api.area'),
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_requests', to='api.area'),
        ),
    ]
