# Generated by Django 6.0.7 on 2026-07-31 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_area_sts_area_wastecollectionrequest_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle (At STS)'), ('collecting', 'Out Collecting'), ('returning', 'Returning to STS')], default='idle', max_length=20),
        ),
        migrations.CreateModel(
            name='WasteTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_tonnes', models.FloatField(help_text='Estimated tonnes STS wants to transfer')),
                ('weight_leaving_sts', models.FloatField(blank=True, help_text='Logged by STS Manager on departure', null=True)),
                ('weight_arriving_landfill', models.FloatField(blank=True, help_text='Logged by Landfill Manager on arrival', null=True)),
                ('status', models.CharField(choices=[('requested', 'Truck Requested by STS'), ('truck_assigned', 'Truck Assigned by Landfill'), ('in_transit', 'In Transit (Left STS)'), ('received', 'Received at Landfill - Verified'), ('flagged', 'Received at Landfill - Discrepancy Flagged')], default='requested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_transfers', to='api.sts')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_transfers', to='api.truck')),
            ],
        ),
    ]
