# Generated by Django 6.0.7 on 2026-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_van_status_wastetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sts',
            name='last_collected',
            field=models.DateTimeField(blank=True, help_text='Time of last truck dispatch', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='base_fuel_cost_per_km',
            field=models.FloatField(default=0.5, help_text='Liters per km when empty'),
        ),
        migrations.AddField(
            model_name='truck',
            name='load_fuel_penalty',
            field=models.FloatField(default=0.05, help_text='Extra liters per km per tonne of load'),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle at Landfill'), ('moving', 'Moving to STS'), ('loading', 'Loading at STS'), ('returning', 'Returning to Landfill')], default='idle', max_length=20),
        ),
    ]
